services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: false

  DVC\ForceYoutubeNocookie\:
    resource: ../src

  DVC\ForceYoutubeNocookie\EventListener\DataContainer\ContentCallbackListener:
    public: true
